### PR TITLE
feat: bullmq support

### LINKED ISSUE #37: add bullmq support
Just need to add bullmq as a project dependency and provide it [in the index script](https://github.com/bee-queue/docker-arena/blob/a7547bd85e8683c3b81de3836173255076b5be09/index.js#L14-L22). Per bee-queue/arena#248.

### PR DESCRIPTION
**Pull request by gtpan77**
Fixes: #37

### CODE REVIEW

**Review by skeggse — APPROVED** [review]
This lgtm. How do you think we want to handle semver? It definitely feels like this is a minor rev (which corresponds to the `feat` tag), but that results in docker-arena's version diverging from upstream. Maybe we publish a dummy version of arena?

**Comment by gtpan77** [comment]
This change also looks like minor revision to me. What other changes we have to do if we want to publish dummy version of arena?

**Comment by skeggse** [comment]
I just mean that we'd republish the same code as in latest arena as a new minor version so they stay in sync. I'll take a look later today.

**Comment by gtpan77** [comment]
Okay, let me know if I can contribute in some way.

**Pull request merged**
